# Generated by Django 5.2.5 on 2025-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen_prenda',
            field=models.CharField(blank=True, help_text='URL de la imagen en Cloudinary', max_length=500, null=True),
        ),
    ]
