# Generated by Django 5.2.5 on 2025-12-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
    ]
