# Generated by Django 5.2.5 on 2025-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='App.usuario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='prenda',
            field=models.ForeignKey(on_delete=models.CASCADE, to='App.prenda'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.ForeignKey(on_delete=models.CASCADE, to='App.tipotransaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='App.fundacion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='campana',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='App.campanafundacion'),
        ),
        migrations.AddField(
            model_name='campanafundacion',
            name='fundacion',
            field=models.ForeignKey(on_delete=models.CASCADE, to='App.fundacion'),
        ),
    ]
