# Generated by Django 5.2.5 on 2025-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa del usuario', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitud para ubicación en mapa', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitud para ubicación en mapa', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_en_mapa',
            field=models.BooleanField(default=False, help_text='¿Permitir que mi ubicación sea visible en el mapa público?'),
        ),
    ]
