# Generated by Django 5.2.5 on 2025-12-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_add_missing_fk_columns'),
    ]

    operations = [
    ]
