# Generated by Django 5.2.5 on 2025-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_foreign_keys_prenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='id',
        ),
        migrations.AddField(
            model_name='prenda',
            name='id_prenda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
