# Generated by Django 5.2.5 on 2025-12-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_change_imagen_prenda_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='beneficios_donacion',
            field=models.TextField(blank=True, help_text='Beneficios de la donación: Explicar los beneficios de donar ropa, como la reducción de desechos y la creación de valor social.', null=True),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='imagenes_adicionales',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales de la fundación (físico, publicaciones, personal, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='responsabilidad_donante',
            field=models.TextField(blank=True, help_text='Responsabilidad del donante: Informar a los donantes sobre la responsabilidad de verificar el estado de la ropa antes de donarla.', null=True),
        ),
    ]
