# Generated by Django 5.2.5 on 2025-12-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_fundacion_beneficios_donacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='imagen_fundacion',
            field=models.CharField(blank=True, help_text='URL de la imagen en Cloudinary', max_length=500, null=True),
        ),
    ]
