# Generated by Django 5.2.5 on 2025-12-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_fix_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.AutoField(db_column='id_transaccion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='impactoambiental',
            name='prenda',
            field=models.ForeignKey(db_column='id_prenda_id', on_delete=django.db.models.deletion.CASCADE, to='App.prenda'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='campana',
            field=models.ForeignKey(blank=True, db_column='id_campana_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.campanafundacion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fundacion',
            field=models.ForeignKey(blank=True, db_column='id_fundacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.fundacion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='prenda',
            field=models.ForeignKey(db_column='id_prenda_id', on_delete=django.db.models.deletion.CASCADE, to='App.prenda'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.ForeignKey(db_column='id_tipo_id', on_delete=django.db.models.deletion.CASCADE, to='App.tipotransaccion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='user_destino',
            field=models.ForeignKey(blank=True, db_column='id_usuario_destino_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='App.usuario'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='user_origen',
            field=models.ForeignKey(db_column='id_usuario_origen_id', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='App.usuario'),
        ),
    ]
