# Generated by Django 5.2.5 on 2025-12-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_transaccion_id_transaccion_id_transaccion_and_more'),
    ]

    operations = [
    ]
