# Generated by Django 5.2.5 on 2025-12-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20251211_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='id',
        ),
        migrations.AlterField(
            model_name='logro',
            name='codigo',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
