# Generated by Django 5.2.5 on 2025-12-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_logro_id_alter_logro_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='id',
        ),
    ]
