# Generated by Django 5.2.5 on 2025-12-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_logro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='codigo_seguimiento_envio',
            field=models.CharField(blank=True, help_text='Código de seguimiento del envío (Shipit u otro)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo del envío calculado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='courier',
            field=models.CharField(blank=True, help_text='Nombre del courier (ej: Chilexpress, Correos, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Dimensiones del paquete (largo x ancho x alto en cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Dirección de entrega/destino para envío', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='direccion_retiro',
            field=models.CharField(blank=True, help_text='Dirección de retiro/origen para envío', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='en_disputa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_disputa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso estimado de la prenda en kilogramos', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='razon_disputa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputas_reportadas', to='App.usuario'),
        ),
    ]
