"""
Django settings for Proyecto project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Bases de datos
import dj_database_url
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables del archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-ljb4n=7yv$*c(q=y&qhxh@7y8@e@7%ezj2=mnbz$x87p$qywgf'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost'
).split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://proyectoecoprenda-ykp.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'App'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middlewares personalizados para gestión de sesiones
    'App.middleware.SessionManagementMiddleware',
    'App.middleware.InactivityLogoutMiddleware',
    'App.middleware.SessionSecurityMiddleware',
    # Middlewares personalizados para cookies
    'App.cookie_middleware.CookieConsentMiddleware',
    'App.cookie_middleware.CookiePreferencesMiddleware',
]

ROOT_URLCONF = 'Proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    # Render o producción: usar PostgreSQL desde DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desarrollo local: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para archivos de media (imágenes subidas por usuarios)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL de login
LOGIN_URL = '/login/'

# Redirección después del login
LOGIN_REDIRECT_URL = 'home'

# Redirección después del logout
LOGOUT_REDIRECT_URL = 'home'

# Configuración de Sesiones

# Motor de sesiones (base de datos es más seguro que archivos)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Duración de la sesión (en segundos)
# 2 horas = 7200 segundos
# 24 horas = 86400 segundos
# 7 días = 604800 segundos
SESSION_COOKIE_AGE = 86400  # 24 horas

# Expirar sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # False = mantiene la sesión según SESSION_COOKIE_AGE

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'ecoprenda_sessionid'

# Seguridad de cookies
SESSION_COOKIE_HTTPONLY = True  # No accesible desde JavaScript
SESSION_COOKIE_SECURE = False  # True solo en HTTPS (cambiar a True en producción)
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF

# Serialización de sesiones
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Configuración de Seguridad

# Protección CSRF
CSRF_COOKIE_HTTPONLY = False  # Debe ser False para que JavaScript pueda leerla
CSRF_COOKIE_SECURE = False  # True en producción con HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'ecoprenda_csrftoken'

# Headers de seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# Agregado: Más headers para mayor seguridad
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Sugerencia: Mejora privacidad

# En producción, descomenta y activa estos (o usa un settings_prod.py separado):
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ==============================================================================
# CONFIGURACIÓN DE LOGGING
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'ecoprenda.log'),
            'formatter': 'verbose',
        },
        'api_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'apis.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'App.cloudinary_utils': {
            'handlers': ['console', 'api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'App.clarifai_utils': {
            'handlers': ['console', 'api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ==============================================================================
# CONFIGURACIÓN DE APIs EXTERNAS
# ==============================================================================
# IMPORTANTE: Todas las credenciales deben estar en el archivo .env
# NUNCA commitear .env a Git (ya está en .gitignore)
# ==============================================================================# ---------------------- GEOAPIFY (Mapas) ----------------------
GEOAPIFY_API_KEY = os.environ.get('GEOAPIFY_API_KEY')
if not GEOAPIFY_API_KEY and not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('GEOAPIFY_API_KEY no está configurada en variables de entorno')

# ---------------------- CLOUDINARY (Imágenes) ----------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# Validar credenciales en producción
if not DEBUG:
    for key, value in CLOUDINARY_STORAGE.items():
        if not value:
            from django.core.exceptions import ImproperlyConfigured
            raise ImproperlyConfigured(f'CLOUDINARY_{key} no está configurada en variables de entorno')

# Usar Cloudinary como almacenamiento por defecto
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Configuración adicional de Cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE.get('CLOUD_NAME', ''),
    api_key=CLOUDINARY_STORAGE.get('API_KEY', ''),
    api_secret=CLOUDINARY_STORAGE.get('API_SECRET', ''),
    secure=True  # Usar HTTPS
)

# ---------------------- CLARIFAI (Detección de Prendas) ----------------------
CLARIFAI_PAT = os.environ.get('CLARIFAI_PAT')
if not CLARIFAI_PAT and not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('CLARIFAI_PAT no está configurada en variables de entorno')

CLARIFAI_USER_ID = 'clarifai'
CLARIFAI_APP_ID = 'main'
CLARIFAI_MODEL_ID = 'apparel-detection'
CLARIFAI_MODEL_VERSION_ID = '1ed35c3d176f45d69d2aa7971e6ab9fe'

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD PARA RENDER / PRODUCCIÓN
# ==============================================================================

if not DEBUG:
    # HTTPS y seguridad en producción
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'